### ISSUE TITLE
Installation Error: error when importing

### ISSUE THREAD

**Issue by ssheybani** [buildingamind/NewbornEmbodiedTuringTest#9] opened 2024-01-29 23:18 UTC
**Describe the bug**

I followed the installation guide, i.e.

conda create -n netts python=3.10.12
conda activate netts

pip install setuptools==65.5.0 pip==21
pip install nett-benchmarks

(I got the following error here:

 Building wheel for gym (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/sheybani/anaconda3/envs/netts/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-installgym_9aaa65d993704e14bd6fab28427dc2cf/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'heel-krklsetf

ERROR: Failed building wheel for gym

but then eventually this was printed:

DEPRECATION: gym was installed using the legacy 'setup.py install' method, because a wheel could not be built for it. A possible repls://github.com/pypa/pip/issues/8368.

and when it finished, i could import gym in python with no error.

but then this gave an error:

from netts import Brain, Body, Environment
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sheybani/anaconda3/envs/netts/lib/python3.10/site-packages/netts/__init__.py", line 20, in <module>
    from netts.environment.builder import Environment
  File "/home/sheybani/anaconda3/envs/netts/lib/python3.10/site-packages/netts/environment/builder.py", line 13, in <module>
    from mlagents_envs.envs.unity_gym_env import UnityToGymWrapper
  File "/home/sheybani/anaconda3/envs/netts/lib/python3.10/site-packages/mlagents_envs/envs/__init__.py", line 5, in <module>
    for key in default_registry:
  File "/home/sheybani/anaconda3/envs/netts/lib/python3.10/site-packages/mlagents_envs/registry/unity_env_registry.py", line 118, in __iter__
    self._load_all_manifests()
  File "/home/sheybani/anaconda3/envs/netts/lib/python3.10/site-packages/mlagents_envs/registry/unity_env_registry.py", line 83, in _load_all_manifests
    manifest = load_remote_manifest(path_to_yaml)
  File "/home/sheybani/anaconda3/envs/netts/lib/python3.10/site-packages/mlagents_envs/registry/binary_utils.py", line 223, in load_remote_manifest
    with open(manifest_path, "wb") as manifest:
PermissionError: [Errno 13] Permission denied: '/tmp/ml-agents-binaries/tmp/6cf1fcd8-939e-4f51-9273-ba25cc0fc14c.yaml'

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu servers at Luddy

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ssheybani** [comment] 2024-01-30 20:05
As the error says, it seems to be a directory access issue. It can be resolved by having sudo access. Some of the servers in the lab also don't require it.

**Comment by Zach-Attach** [comment] 2024-01-30 21:25
The cause of the error is a result of mlagents creating a directory in `/tmp/` called `/tmp/ml-agents-binaries`, but the directory is only accessible to the user who created it, so only the user who first runs the code can run on that server. An easy solution is for the user who owns that tmp directory to run `rm -rf "/tmp/ml-agents-binaries"` after running netts.

**Comment by Zach-Attach** [comment] 2024-01-30 21:32
Another solution might be to run `chmod 1777 /tmp` to give everyone access to this directory in `/tmp/` without allowing deletions of others code (see https://unix.stackexchange.com/questions/71622/what-are-correct-permissions-for-tmp-i-unintentionally-set-it-all-public-recu)

**Comment by Zach-Attach** [comment] 2024-01-31 01:43
Might be able to get around this by editing the tmp_dir for ml-agents (see [this code](https://github.com/Unity-Technologies/ml-agents/blob/f442194297f878a84eb60c04eccf7662cbc9ff60/ml-agents-envs/mlagents_envs/registry/binary_utils.py#L109) ). The only possible way I can see how to edit this seems to be through [registries](https://github.com/Unity-Technologies/ml-agents/blob/f442194297f878a84eb60c04eccf7662cbc9ff60/docs/Unity-Environment-Registry.md?plain=1#L12) but I am not certain

**Comment by desaibhargav** [comment] 2024-01-31 03:21
Hi @ssheybani, thanks for reporting the issue. Regarding the first error, this is a known issue during `gym` installation where it reverts to a legacy `setup.py` install. If you could import `gym` and there were no further errors, `nett-benchmarks` installed fine. 

As @Zach-Attach mentions, it's a permission issue and should be fixed by his suggestions. Did it resolve the issue? 

It is odd for this to happen in any case, and I'd love to dive deeper on this on Friday.

**Comment by Zach-Attach** [comment] 2024-01-31 15:20
I was able to fix @ssheybani 's issue by running `rm -rf /tmp/ml-agents` after realizing the ownership patterns of the directory from `ls -l /tmp/ml-agents`. Running chmod should resolve issues but is currently unconfirmed.

**Comment by Zach-Attach** [comment] 2024-01-31 15:30
Given that this appears to be focused on the `/tmp/` issue which was blocking installation, I am moving the gym wheel issue to #12 
@ssheybani please include any information you have on the particular issue there. Maybe it will be fixed one day.

**Comment by Zach-Attach** [comment] 2024-02-07 20:08
For anyone wondering, the solution is to run `chmod 1777 /tmp/ml-agents-binaries`, `chmod 1777 /tmp/ml-agents-binaries/tmp`, and `chmod 1777 /tmp/ml-agents-binaries/binaries`. 

This is because ml-agents 1.0.0 currently runs `chmod 755` on these directories, but this blocks other users from adding their own files to the directory. Users need read, write, and execute (`7`) privileges to these directories in order to add their own files. The `1` at the beginning is added to prevent other users from deleting these directories while remaining to have write access.

Ideally, ml-agents should do one of the following:
1) add a hash string or timestamp to the end of the `/tmp/ml-agents-binaries` directory, so that each instance of it does not clash
2) save these files to a directory inside `ml-agents` itself and delete them afterwards
3) run `chmod 1777` to these directories instead of `755` as they currently have it

**Comment by Zach-Attach** [comment] 2024-02-07 20:08
Added code to ensure that permissions are set correctly in #26

**Closed** 2024-02-07 20:09 UTC
Labels: bug, installation
